name: Concurrency Workflow
run-name: "Concurrency workflow run for ${{ github.event.inputs.environment }}"
on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Enter a environment name"
                required: true
                type: environment
jobs:
    concurrency-job:
        runs-on: ubuntu-latest
        concurrency:
            group: concurrency1
            cancel-in-progress: true
        steps:
            - name: Sleep 30 seconds
              run: sleep 30
