name: Display Directories Info
on: [push]
jobs:
    display-dir-info:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v2
            - name: Display Directories Info
              run: |
                  pwd
                  ls -la
                  echo $GITHUB_WORKSPACE
                  echo $GITHUB_REPOSITORY
                  echo $GITHUB_SHA
            - name: Change Working Directory
              working-directory: /home/runner
              run: |
                  pwd
                  ls -la
    display-dir-info-windows:
        runs-on: windows-latest
        defaults:
            run:
                shell: pwsh
        steps:
            - uses: actions/checkout@v2
            - name: Display Directories Info
              run: |
                  Get-Location
                  dir
                  echo $GITHUB_WORKSPACE
                  echo $GITHUB_REPOSITORY
                  echo $GITHUB_SHA
            - name: Commande python
              shell: python
              run: |
                  import platform
                  print(platform.system())
