name: External trigger workflow
on:
    repository_dispatch:
        types: [build]
jobs:
    external-trigger:
        runs-on: ubuntu-latest
        steps:
            - name: afficher les parametres
              run: |
                  echo "Environment: ${{ github.event.client_payload.environment }}"
                  echo "Version: ${{ github.event.client_payload.version }}"
