name: Matrix workflow
on: [push]
jobs:
    matrix-job:
        runs-on: ${{ matrix.os }}
        continue-on-error: false
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                node: [20, 21, 22]
                include:
                    - os: ubuntu-latest
                      is-ubuntu: true
                    - experimental: false
                    - os: macos-latest
                      node: 22
                    - os: ubuntu-latest
                      node: 20
                    - os: ubuntu-latest
                      node: 21
                      experimental: true
                exclude:
                    - os: ubuntu-latest
                      node: 21
            fail-fast: true
        steps:
            - if: matrix.experimental == true
              run: exit 1
            - name: Node version before setup
              run: node --version
            - run: echo "${{ toJSON(matrix) }}"
            - name: Set up Node.js ${{ matrix.node }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
            - name: Node version after setup
              run: node --version
