name: Matrix workflow
on: [push]
jobs:
    matrix-job:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                node: [20, 21, 22]
        steps:
            - name: Node version before setup
              run: node --version
            - name: Set up Node.js ${{ matrix.node }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
            - name: Node version after setup
              run: node --version
