name: Workflow caller
on:
    workflow_dispatch:
        inputs:
            name:
                description: "Enter your environment"
                required: true
                type: string
                default: "Mohamed"
jobs:
    call-workflow:
        uses: gh-course/workflows/.github/workflows/reusable.yaml@main
        with:
            name: ${{ github.event.inputs.name }}
        secrets:
            access-token: ${{ secrets.ACCESS_TOKEN }}
    use-reusable-wf-in-the-same-repo:
        uses: ./.github/workflows/reusable-workflow.yaml
    use-reusable-wf-output:
        runs-on: ubuntu-latest
        needs: use-reusable-wf-in-the-same-repo
        steps:
            - name: Display the output date
              run: echo "The output date is ${{ needs.use-reusable-wf-in-the-same-repo.outputs.date }}"
